# Extract data from the givenSalaryGender CSV fileand store the data from each column in a separate NumPy array.

In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('dataset/SalaryGender.csv')

In [7]:
data

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
2     35.1       0   56    0
3     30.0       1   23    0
4     80.0       0   53    1
..     ...     ...  ...  ...
95    18.6       1   26    0
96   152.0       1   56    1
97     1.8       1   28    0
98    35.0       0   44    0
99     4.0       0   24    0

[100 rows x 4 columns]

In [15]:
salary = np.array(data['Salary'])
gender = np.array(data['Gender'])
age = np.array(data['Age'])
phD = np.array(data['PhD'])

In [16]:
salary

array([140.  ,  30.  ,  35.1 ,  30.  ,  80.  ,  30.  ,  60.  ,  31.1 ,
       125.  ,  51.  ,   3.  ,  46.  , 150.  ,   3.  , 130.  ,  15.  ,
       130.  ,  84.  , 190.  ,  74.  ,  73.  ,  10.  ,  50.  ,   7.  ,
         9.5 ,  15.2 ,  28.6 ,  20.  ,  72.  ,  81.  , 100.  ,  90.  ,
        90.  ,  35.  ,  30.  ,  25.  ,  52.  ,   9.  ,  63.  ,  72.  ,
        16.  ,  92.  , 106.  ,   2.5 ,   9.  ,  32.  ,  32.  ,  55.  ,
        52.  ,  28.  ,  20.  ,  14.7 ,  22.3 ,  34.8 ,  84.  ,  19.  ,
       160.  ,  65.  ,  55.  ,   4.6 , 102.  ,  20.  ,  62.  ,  55.  ,
        45.6 ,  40.  ,  24.  ,  35.  ,  48.  ,  20.  ,  40.7 ,  15.  ,
         0.25, 152.  ,  39.8 ,  12.  ,  30.  , 120.  ,   1.7 ,  36.  ,
        96.  ,  38.  ,  90.  ,   9.  ,  25.8 ,  22.  ,  38.8 ,  72.  ,
        89.  ,  41.  ,  89.  ,  25.  ,  52.  , 115.  ,  66.  ,  18.6 ,
       152.  ,   1.8 ,  35.  ,   4.  ])

In [17]:
gender

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0])

In [18]:
age

array([47, 65, 56, 23, 53, 27, 53, 30, 44, 63, 22, 59, 60, 28, 65, 25, 65,
       47, 66, 45, 46, 24, 60, 63, 27, 66, 36, 30, 51, 65, 45, 52, 54, 30,
       52, 26, 49, 22, 34, 60, 28, 58, 77, 67, 27, 48, 45, 49, 36, 65, 32,
       49, 67, 22, 49, 43, 61, 43, 52, 51, 66, 29, 62, 56, 61, 56, 41, 24,
       60, 43, 57, 23, 53, 71, 20, 27, 69, 58, 37, 32, 33, 32, 60, 71, 30,
       62, 54, 42, 62, 51, 71, 29, 55, 54, 55, 26, 56, 28, 44, 24])

In [19]:
phD

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0])

# Find1. The number of men with a PhD2. The number of women with a PhD

In [31]:
dphd_female = data[(data['Gender']==1) &  (data['PhD']==1)].count()  #and data['PhD']==1]

In [32]:
dphd_female

Salary    24
Gender    24
Age       24
PhD       24
dtype: int64

In [33]:
dphd_male = data[(data['Gender']==0) &  (data['PhD']==1)].count()

In [34]:
dphd_male

Salary    15
Gender    15
Age       15
PhD       15
dtype: int64

# Store the "Age"and "Ph.D."columns in one DataFrameand delete the data of all people who don't have a Ph.D.from SalaryGender CSV file.

In [35]:
data_age_salary = data.iloc[:,2:]

In [37]:
data_age_salary = data_age_salary[data_age_salary['PhD']==1]

In [38]:
data_age_salary

Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1

# Calculate the total number of people who have a Ph.D.degreefrom the SalaryGender CSV file.

In [40]:
data.shape

(100, 4)

In [45]:
count =0
for i in range(0,100):
    if(phD[i]==1):
        count+=1

In [46]:
count

39

# How  do  you count the frequency  ofeach  value  appearingin the  givenarray  of integers?[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

In [47]:
sample_array = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])

In [51]:
sample_array.mean()

2.7142857142857144

In [54]:
set_val = set(sample_array)

In [57]:
dictionary ={}
for val in set_val:
    dictionary[val]=0

In [59]:
count=0
for i in range(0,14):
     dictionary[sample_array[i]]+=1

In [60]:
dictionary

{0: 4, 1: 2, 2: 1, 3: 1, 4: 3, 5: 2, 9: 1}

In [53]:
help("numpy.array.")

Help on built-in function array in numpy.array:

numpy.array. = array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
    

In [61]:
np.bincount(sample_array)

array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1])

# Create a NumPyarray [[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]]) and filter the elements greater than 5

In [62]:
sample_array = np.array([[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]])

In [63]:
sample_array.shape

(4, 3)

In [65]:
for i in range(4):
    for j in range(3):
        if (sample_array[i][j]>5):
            print("value at ({},{}) is {} and is greater than 5".format(i,j,sample_array[i][j]))

value at (2,0) is 6 and is greater than 5
value at (2,1) is 7 and is greater than 5
value at (2,2) is 8 and is greater than 5
value at (3,0) is 9 and is greater than 5
value at (3,1) is 10 and is greater than 5
value at (3,2) is 11 and is greater than 5


# Create a NumPyarray having NaN (Not a Number) and print it.array([ nan,   1.,   2.,  NaN,   3.,   4.,   5.])Print the same array omitting all elements,which are NaN.

In [68]:
sample_array = np.array([ np.NaN, 1., 2., np.NaN, 3., 4., 5.])

In [69]:
sample_array

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [72]:
sample_array[~np.isnan(sample_array)]

array([1., 2., 3., 4., 5.])

# Create  a  10x10  array  with  random values  and  find  the  minimum  and  maximum values.

In [73]:
sample_array = np.random.random((10,10))

In [74]:
sample_array

array([[0.8027188 , 0.2974619 , 0.78197564, 0.1374321 , 0.43941289,
        0.05271721, 0.83736915, 0.07530259, 0.54356522, 0.71191909],
       [0.11190703, 0.77388881, 0.461835  , 0.70172983, 0.65277689,
        0.34112824, 0.97024159, 0.0522853 , 0.31647657, 0.97108529],
       [0.16891646, 0.27123283, 0.30210741, 0.84072667, 0.28503544,
        0.89099415, 0.16807915, 0.62522519, 0.47325067, 0.71470598],
       [0.42648001, 0.04569799, 0.65857791, 0.43804266, 0.40771696,
        0.53379241, 0.03086654, 0.99893264, 0.44206428, 0.80726929],
       [0.50240517, 0.94332012, 0.78162764, 0.8842142 , 0.24051901,
        0.52269782, 0.78245545, 0.32609359, 0.42093175, 0.05257481],
       [0.68385787, 0.4042757 , 0.70430654, 0.9929554 , 0.84057038,
        0.69083227, 0.00105569, 0.6547756 , 0.70029442, 0.80730887],
       [0.76053674, 0.98233815, 0.16901186, 0.22975788, 0.52816881,
        0.70402074, 0.92655681, 0.33223265, 0.46707304, 0.77983237],
       [0.3815141 , 0.48538096, 0.6794588

In [76]:
min_val,max_val = sample_array.min(),sample_array.max()

In [77]:
print(min_val,max_val)

0.001055694450394773 0.9989326400245299


# Create a random vector of size 30 and find the mean value.


In [78]:
sample_vec = np.random.random(30)

In [79]:
sample_vec.mean()

0.42737495748531446

# Create a NumPyarray  having  elements  0  to  10  And  negate  all  the  elements between 3 and 9.

In [98]:
sample_array = np.random.randint(0,10,10)
#sample_array= np.arange(11)

In [99]:
sample_array

array([7, 3, 9, 5, 6, 8, 2, 8, 9, 8])

In [102]:
sample_array[(sample_array>3) | (sample_array<=8)]*=-1

In [103]:
sample_array

array([-7, -3,  9, -5, -6,  8,  2,  8,  9,  8])

# Create a random array of 3 rows and 3 columns and sort it according tothefirst, second,or thirdcolumn.

In [104]:
sample_array = np.random.random((3,3))

In [105]:
sample_array

array([[0.54204162, 0.22696653, 0.74242968],
       [0.1991913 , 0.62882489, 0.1158201 ],
       [0.39764733, 0.82557955, 0.72888899]])

In [111]:
print(sample_array[sample_array[:,0].argsort()])
print("----------------")
print(sample_array[sample_array[:,1].argsort()])
print("----------------")
print(sample_array[sample_array[:,2].argsort()])

[[0.1991913  0.62882489 0.1158201 ]
 [0.39764733 0.82557955 0.72888899]
 [0.54204162 0.22696653 0.74242968]]
----------------
[[0.54204162 0.22696653 0.74242968]
 [0.1991913  0.62882489 0.1158201 ]
 [0.39764733 0.82557955 0.72888899]]
----------------
[[0.1991913  0.62882489 0.1158201 ]
 [0.39764733 0.82557955 0.72888899]
 [0.54204162 0.22696653 0.74242968]]


# Create a four dimensions arraytogetthesum over the last two axes at once.

In [112]:
sample_array = np.random.random((3,3,3,3))

In [113]:
sample_array

array([[[[0.79757969, 0.38695065, 0.35064616],
         [0.7167738 , 0.28366832, 0.27031884],
         [0.47671144, 0.08813368, 0.2910725 ]],

        [[0.34470157, 0.76735654, 0.78834137],
         [0.52484238, 0.70191307, 0.38494228],
         [0.62617565, 0.03429047, 0.99603584]],

        [[0.57577143, 0.04422469, 0.24468093],
         [0.65637507, 0.62833477, 0.44996362],
         [0.34467815, 0.71573707, 0.27955272]]],


       [[[0.34098503, 0.08938603, 0.91269124],
         [0.18959086, 0.3940855 , 0.86374817],
         [0.82865133, 0.48029633, 0.3548354 ]],

        [[0.64234043, 0.367625  , 0.74806776],
         [0.28336656, 0.87464857, 0.72482443],
         [0.16626027, 0.11905615, 0.27804792]],

        [[0.70776476, 0.2122949 , 0.43514467],
         [0.78224398, 0.0429412 , 0.91672331],
         [0.90325536, 0.16761953, 0.62640429]]],


       [[[0.32279868, 0.66812721, 0.72105577],
         [0.32604705, 0.036743  , 0.76431222],
         [0.90857395, 0.85493426, 0.65130206

In [124]:
sample_array.reshape(sample_array.shape[:-2]+(-1,)).sum(axis =1)

array([[1.71805269, 1.19853188, 1.38366846, 1.89799124, 1.61391615,
        1.10522474, 1.44756525, 0.83816123, 1.56666105],
       [1.69109022, 0.66930593, 2.09590367, 1.2552014 , 1.31167527,
        2.50529591, 1.89816696, 0.76697201, 1.25928761],
       [1.46670906, 1.97951103, 1.5502343 , 0.84245629, 0.43952514,
        2.56728877, 2.15951809, 2.19673791, 2.02161718]])

# Create a random array and swap two rows of an array

In [129]:
sample=np.random.randint(0,10,(3,3))

In [130]:
sample

array([[4, 2, 1],
       [8, 8, 2],
       [6, 6, 5]])

In [133]:
sample[[0,1]]

array([[4, 2, 1],
       [8, 8, 2]])

In [134]:
sample[[1,0]]

array([[8, 8, 2],
       [4, 2, 1]])

In [135]:
sample[[0,1]]=sample[[1,0]]

In [136]:
sample

array([[8, 8, 2],
       [4, 2, 1],
       [6, 6, 5]])

# Create a random matrix and compute thematrix rank

In [144]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10
